### PR TITLE
Bring back the old behavior for the GC being applied on the feature transformer weights.

### LINKED ISSUE #101: Ranger GC when the weights are transposed.
With the introduction of the new kernel the weights of the feature transformer are now transposed, which means ranger's GC is applied on a different axis. Maybe that's the source of the regression? Will try to disable GC and will have more data tomorrow.

This investigation follows a weird regression from vondele and weird evaluations favoring black even in startpos in my recent nets.

### PR DESCRIPTION
**Pull request by Sopel97**
Fixes #101

### CODE REVIEW

**Comment by Sopel97** [comment]
master vs (half of this) patch. On a different branch so loss is not comparable directly.
plot_52_53_split

**Comment by vondele** [comment]
IMO, good to get this in soon. 

Probably wise to test the full version of this patch as well. If you haven't done so yet.

**Comment by Sopel97** [comment]
I have not, but I will have a comparison in about 24 hours.

**Comment by Sopel97** [comment]
I was incorrect. The other codepath that I have not modified for the tests is not taken with our parameters. Therefore the tests above reflect a fully fixed version.

**Pull request merged**
