### PR TITLE
Add GPLv3 license notice.

### LINKED ISSUE #151: Add license to repository
- I would like to fork the repository and modify some code for my own experiments. Ideally, I would like to put the result of these experiments in a different Github repository.
- Please add a license to make this valid. I suggest to use the GPL 3.0 license as for Stockfish.
- [Reason](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license): "If a repository has no license, then all rights are reserved and it is not Open Source or Free. You cannot modify or redistribute this code without explicit permission from the copyright holder."

### PR DESCRIPTION
**Pull request by Sopel97**
Closes #151 

It was brought to attention that this reposity does not contain any license. It would make sense to license it with GPLv3, to match Stockfish, but if there are strong objections we can consider a different license. This better be done early as it requires an agreement from all authors.

- [x] @Sopel97 
- [x] @glinscott 
- [x] @vondele 
- [x] @ddobbelaere 
- [x] @sergiovieri 
- [x] @niklasf 
- [x] @kennyfrc 
- [x] @nodchip 
- [ ] @Nomoras (only docs)

I'd appreciate every pinged person to give a clear answer below.

### CODE REVIEW

**Comment by nodchip** [comment]
I agree to license with GPLv3.

**Comment by vondele** [comment]
OK with me

**Comment by kennyfrc** [comment]
Ok with me

**Comment by niklasf** [comment]
Ok with me

**Comment by ddobbelaere** [comment]
OK with me

**Comment by glinscott** [comment]
Oops, should have done this from the start.  yes, looks good to me

**Comment by sergiovieri** [comment]
OK with me

**Comment by vondele** [comment]
@Nomoras had a contribution to the documentation. It would be nice to have his OK, but GPL and docs is a corner case.

All code contributions are covered, we can add the license.

**Pull request merged**
