### PR TITLE
Add blocked sparse input affine transform approach to docs.

### PR DESCRIPTION
**Pull request by Sopel97**
Based on https://github.com/official-stockfish/Stockfish/pull/4612

### CODE REVIEW

**Comment by vondele** [comment]
I have read through this, looks OK. 

Independent from this PR, should we integrate the permutation code (as mentioned https://github.com/official-stockfish/Stockfish/pull/4620#issue-1757202863) in the trainer somehow ?

**Comment by Sopel97** [comment]
> Independent from this PR, should we integrate the permutation code (as mentioned https://github.com/official-stockfish/Stockfish/pull/4620#issue-1757202863) in the trainer somehow ?

We could maybe apply it during serialization if we have a good enough solution. Right now we should work on a separate tool. I made some initial scaffolding here https://github.com/Sopel97/nnue-pytorch/blob/ftperm/ftperm.py

**Comment by vondele** [comment]
I think the greedy permutation that is used in the SF PR mentioned is likely a near-optimal solution to do this.

Computing the permutation needs some 50M positions, which in principle we can do by just using that many from a binpack and doing inference. Right now this is some modified version of SF collecting that data, but that's not ideal.

**Comment by vondele** [comment]
anyway, docs seem complete. Ready for a merge?

**Comment by Sopel97** [comment]
yes

**Pull request merged**
