### PR TITLE
Change sigmoid scaling.

### PR DESCRIPTION
**Pull request by Sopel97**
I've ran 4 tests.
exp_10 - master
exp_11 - in_scaling from 361 to 410 (matching input data of vondele's d9)
exp_12 - exp_11 but out_scaling from 361 to 600
exp_13 - exp_11 but out_scaling from 361 to 800

plot_10_11
plot_11_12
plot_11_13

matches ran at 50k nodes per move (can't run fixed time because HT)
exp_10 (note, the checkpoints were more scarce than in the future tests):
```
   # PLAYER                                                :  RATING  ERROR   POINTS  PLAYED   (%)  CFS(%)
   1 master                                                :     0.0   ----  83613.5  151525    55     100
   2 ../nnue-pytorch-training/experiment_10/run_0/nn-epoch314.nnue   :   -12.3    6.6   2316.0    4800    48      70
   3 ../nnue-pytorch-training/experiment_10/run_1/nn-epoch224.nnue   :   -14.3    3.1   8729.0   18200    48      91
   4 ../nnue-pytorch-training/experiment_10/run_3/nn-epoch179.nnue   :   -17.7    4.1   7121.5   15000    47      66
   5 ../nnue-pytorch-training/experiment_10/run_1/nn-epoch154.nnue   :   -18.9    3.7   6245.0   13200    47      68
   6 ../nnue-pytorch-training/experiment_10/run_0/nn-epoch179.nnue   :   -20.4    4.8   4050.5    8600    47      88
   7 ../nnue-pytorch-training/experiment_10/run_2/nn-epoch159.nnue   :   -25.1    6.2   2042.5    4400    46      54
   8 ../nnue-pytorch-training/experiment_10/run_3/nn-epoch174.nnue   :   -25.6    6.8   1854.0    4000    46      55
   9 ../nnue-pytorch-training/experiment_10/run_1/nn-epoch179.nnue   :   -26.3    8.2   1480.0    3200    46      55
  10 ../nnue-pytorch-training/experiment_10/run_1/nn-epoch84.nnue   :   -27.0    5.9   2954.0    6400    46      50
```

exp_11:
```
   # PLAYER                                                :  RATING  ERROR    POINTS  PLAYED   (%)  CFS(%)
   1 master                                                :     0.0   ----  104804.5  186600    56      99
   2 ../nnue-pytorch-training/experiment_11/run_2/nn-epoch259.nnue   :   -11.6   10.1     967.0    2000    48      51
   3 ../nnue-pytorch-training/experiment_11/run_2/nn-epoch174.nnue   :   -11.7    9.1    1450.0    3000    48      52
   4 ../nnue-pytorch-training/experiment_11/run_3/nn-epoch329.nnue   :   -12.0   11.5     676.0    1400    48      51
   5 ../nnue-pytorch-training/experiment_11/run_3/nn-epoch264.nnue   :   -12.1    9.7    1062.0    2200    48      63
   6 ../nnue-pytorch-training/experiment_11/run_3/nn-epoch304.nnue   :   -15.4   16.1     478.0    1000    48      50
   7 ../nnue-pytorch-training/experiment_11/run_3/nn-epoch244.nnue   :   -15.5   10.7     669.0    1400    48      50
   8 ../nnue-pytorch-training/experiment_11/run_3/nn-epoch249.nnue   :   -15.5   12.0     669.0    1400    48      50
   9 ../nnue-pytorch-training/experiment_11/run_3/nn-epoch239.nnue   :   -15.6   12.3     764.5    1600    48      52
  10 ../nnue-pytorch-training/experiment_11/run_2/nn-epoch284.nnue   :   -16.1   12.9     572.5    1200    48      52
```

exp_12:
```
   # PLAYER                                                :  RATING  ERROR    POINTS  PLAYED   (%)  CFS(%)
   1 ../nnue-pytorch-training/experiment_12/run_1/nn-epoch304.nnue   :     0.9    9.6    1403.5    2800    50      57
   2 master                                                :     0.0   ----  106735.5  193200    55      63
   3 ../nnue-pytorch-training/experiment_12/run_1/nn-epoch259.nnue   :    -1.6    9.3    1194.5    2400    50      56
   4 ../nnue-pytorch-training/experiment_12/run_1/nn-epoch299.nnue   :    -2.6    9.5    1191.0    2400    50      57
   5 ../nnue-pytorch-training/experiment_12/run_1/nn-epoch229.nnue   :    -3.8    9.1    1187.0    2400    49      55
   6 ../nnue-pytorch-training/experiment_12/run_1/nn-epoch264.nnue   :    -4.7   11.5     986.5    2000    49      55
   7 ../nnue-pytorch-training/experiment_12/run_1/nn-epoch329.nnue   :    -6.0   15.0     491.5    1000    49      52
   8 ../nnue-pytorch-training/experiment_12/run_0/nn-epoch329.nnue   :    -6.4   13.8     589.0    1200    49      56
   9 ../nnue-pytorch-training/experiment_12/run_1/nn-epoch269.nnue   :    -7.7   10.7     782.5    1600    49      50
  10 ../nnue-pytorch-training/experiment_12/run_0/nn-epoch284.nnue   :    -7.8   12.1     684.5    1400    49      51
```

exp_13:
```
   # PLAYER                                                :  RATING  ERROR    POINTS  PLAYED   (%)  CFS(%)
   1 master                                                :     0.0   ----  110877.5  196000    57      98
   2 ../nnue-pytorch-training/experiment_13/run_1/nn-epoch219.nnue   :    -9.4    9.1    1460.0    3000    49      60
   3 ../nnue-pytorch-training/experiment_13/run_2/nn-epoch309.nnue   :   -11.2   11.5     774.5    1600    48      52
   4 ../nnue-pytorch-training/experiment_13/run_2/nn-epoch324.nnue   :   -11.6   11.9     773.5    1600    48      52
   5 ../nnue-pytorch-training/experiment_13/run_3/nn-epoch224.nnue   :   -12.0   10.1    1062.5    2200    48      53
   6 ../nnue-pytorch-training/experiment_13/run_2/nn-epoch329.nnue   :   -12.6   13.4     578.5    1200    48      54
   7 ../nnue-pytorch-training/experiment_13/run_2/nn-epoch254.nnue   :   -13.5   10.7     961.5    2000    48      52
   8 ../nnue-pytorch-training/experiment_13/run_3/nn-epoch279.nnue   :   -13.8   11.4     768.5    1600    48      50
   9 ../nnue-pytorch-training/experiment_13/run_1/nn-epoch244.nnue   :   -13.8   10.4     768.5    1600    48      52
  10 ../nnue-pytorch-training/experiment_13/run_3/nn-epoch329.nnue   :   -14.3   13.2     575.5    1200    48      50
```
(since error bars are around 10 the trends are more important here)

The results are biased towards better elo, but they don't seem to be due to variance, see: 
- best exp_10 net: https://tests.stockfishchess.org/tests/view/604f3eb82433018de7a38b43
- best exp_12 net: https://tests.stockfishchess.org/tests/view/604f381a2433018de7a38b40
- 
From this we can kinda estimate that `out_scaling` has a sweet spot around 600.
`in_scaling` of 410 compared to 361 is not a big change so it's not reflected by elo, but at least the loss was visibly smaller. While it depends on the data I think it's okay to change the default, considering that most data being used is around depth 9

### CODE REVIEW

**Comment by vondele** [comment]
changing the loss function (e.g. in_scaling) will of course change the loss, so can't be compared to the others. 

However, if the results is an improvement on fishtest, I'm fine with it.

**Comment by Sopel97** [comment]
I just realized I didn't specify the correct master version for one of the tests. I'll redo it...

**Comment by Sopel97** [comment]
So after all it seems there's no measurable difference at least between the nets from top of exp_12 and exp_10 ordo...
new test here: https://tests.stockfishchess.org/tests/view/604fad042433018de7a38b6d

So might not be enough for a merge by our standards.. I'll still use this setup probably as it makes more sense to me.

**Comment by vondele** [comment]
I think we should try to keep our suggestion on best training command as simple as possible, basically what we used for the best net so far, and indeed be conservative when merging. Getting the last few Elo was rather difficult, ideally we don't regress. On that topic, I was never able to reproduce the best net after we fixed the bug with the initialization of the factorizer a while ago. I'm not sure if that was just bad luck, or if that buggy init had something right nevertheless.

**Comment by Sopel97** [comment]
Just for future reference. I took gensfen_multipvdiff_100_d9.binpack from https://drive.google.com/drive/folders/1yLCEmioC3Xx9KQr4T7uB6GnLm5icAYGU and looked at the score distribution.
gensfen_multipvdiff_100_d9
This is what I used for `in_scaling`, 410.

Then I rescored this binpack (up to 2 million positions) with static pure nnue eval of nodchip master (some late december build) and ran the script again.
gensfen_multipvdiff_100_d9_static
Two things to notice.
1. The sigmoid scaling changed to 576 (which is close to my `out_scaling` of 600
2. The sigmoid doesn't match the data very well, it looks more linear in many places, not sure how to interpret this.

**Pull request closed without merging**
