### PR TITLE
Add SFNNv6 architecture to docs with a new diagram

### PR DESCRIPTION
**Pull request by linrock**
Basically took SFNNv5 architecture diagram and replaced 1024 -> 1536 and 512 -> 768. Not sure if that's correct.

### CODE REVIEW

**Comment by Sopel97** [comment]
Please include the .drawio file too

**Comment by linrock** [comment]
Added 3x drawio files for SFNNv6 along with the exported svg files

**Comment by Sopel97** [comment]
I think the others are exported with white background explicitly, because on github dark mode it's illegible.

**Comment by linrock** [comment]
Fixed exported svgs by explicitly not using dark mode when exporting the drawio files

**Comment by Sopel97** [comment]
thanks

**Pull request merged**
