### PR TITLE
[RFC] nnue.md - a detailed walkthrough for nnue

### PR DESCRIPTION
**Pull request by Sopel97**
I'm in the process of writing a sizable document describing all the important knowledge about nnue that we have, from the big picture to the details. I have written some of it already so I thought that I could publish it as a draft PR to get some comments and to be able to link people here already whenever needed.

I have not made any revisions yet, so the style of the writing does change throughout the document as I get more comfortable in writing it. This a very early version and there may be stuff missing even at the begining. This is maybe 30% done.

### CODE REVIEW

**Comment by vondele** [comment]
I haven't yet read fully through, but this is very nice!

**Comment by glinscott** [comment]
Wow, that is a really impressive piece of work!

**Comment by Sopel97** [comment]
This just grew quite sizably. Added quantization, optimized inference, and optimized training stuff.

**Comment by Sopel97** [comment]
I've covered most of the topics I wanted. It's not ready for merge.

**Pull request merged**
