### PR TITLE
Use smaller initial LR

### PR DESCRIPTION
**Pull request by vondele**
lead to a new master net https://github.com/official-stockfish/Stockfish/pull/3848
this is in combination with a restart from a good net (previous master). Visually,
the net starts a bit better after the restart, probably logical as the initial perturbations
are smaller.

### CODE REVIEW

**Comment by Sopel97** [comment]
I think we should instead add an "lr" option to the train script. The right LR may be different for the retraining process compared to training from scratch.

**Comment by vondele** [comment]
yes, it would be good to have a few things more as an option. This makes it somewhat easier to test as well. Nevertheless, good defaults are needed, and I propose using those that lead to a net in master is the safe bet. 

I'll see if I can update the PR later today/this week.

**Comment by Sopel97** [comment]
Perhaps we could only apply this LR change if training from model? I.e. when either `resume_from_checkpoint` or `resume-from-model` is used.

**Comment by vondele** [comment]
I think too much 'smart logic' leads to unexpected behaviour, better have it explicit.

**Comment by Sopel97** [comment]
I will insist at least on a comment specifying that `LR = 8.75e-4` may yield better results when training networks from scratch.

**Comment by vondele** [comment]
yes, I think we should probably document the best options for training from scratch vs restarts... as said, establish the full procedure for training from scratch (which, as I understand, includes retraining cycles).

**Comment by vondele** [comment]
led to another master net https://github.com/official-stockfish/Stockfish/pull/3870

However, some experiments training from scratch shows indeed that this is not optimal for that purpose, only for retraining. As such, shouldn't be merged in this form. Keeping open for the time being.

**Comment by Sopel97** [comment]
superseeded by new arch trainer PR #164

**Pull request closed without merging**
